# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_series', models.CharField(blank=True, max_length=10, null=True)),
                ('item_number', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('status_datetime', models.DateTimeField()),
                ('created_on', models.DateTimeField()),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='collectionitems',
            name='collection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colecoes.Collections', verbose_name='the related collection'),
        ),
    ]
