# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collections',
            new_name='Collection',
        ),
        migrations.RenameModel(
            old_name='CollectionItems',
            new_name='CollectionItem',
        ),
    ]
