# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0003_auto_20160423_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection_item',
            old_name='collection_id',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='collection_type',
            old_name='collection_type_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='status',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='status_datetime',
        ),
        migrations.RemoveField(
            model_name='collection_type',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='collection_type',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='collection_type',
            name='status',
        ),
        migrations.RemoveField(
            model_name='collection_type',
            name='status_datetime',
        ),
        migrations.RemoveField(
            model_name='user_collection',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='user_collection',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user_collection',
            name='status_datetime',
        ),
        migrations.RemoveField(
            model_name='user_collection_item',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='user_collection_item',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user_collection_item',
            name='status_datetime',
        ),
    ]
