# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0007_user_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_message',
            name='message_read_date',
            field=models.DateTimeField(null=True),
        ),
    ]
